version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8080"
    env_file: .env
    environment:
      - PORT=8080
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

